API_HOST_URL: 'https://etraining.moe.gov.sa'
ENVIRONMENT_DISPLAY_NAME: 'etraining.moe.gov.sa'
PLATFORM_NAME: 'MOE'
PLATFORM_DESTINATION_NAME: 'etraining.moe.gov.sa'
FEEDBACK_EMAIL_ADDRESS: 'support@ilearn.ws'
#OAUTH_ENFORCE_SECURE: true
PUSH_NOTIFICATIONS: true
USER_PROFILES_ENABLED: true
DEBUG: true
OAUTH_CLIENT_ID: '2c03c507cadfe54ac028' # PROD
#ENABLE_MOBILE_REST_API: true
MY_VIDEOS_ENABLED: true
DISCUSSIONS_ENABLED: true
COURSE_VIDEOS_ENABLED: true
COURSE_ENROLLMENT : { TYPE : 'native', SEARCH_BAR_ENABLED : true }
SSO_AUTH_URL: 'https://etraining.moe.gov.sa/oauth2/authorize/?scope=openid+profile+email+permissions&state=xyz&redirect_uri=https://etraining.moe.gov.sa/api/mobile/v0.5/?app=android&response_type=code&client_id=2c03c507cadfe54ac028'
ACCESS_TOKEN_REQUEST_URL: 'https://etraining.moe.gov.sa/oauth2/access_token'
ACCESS_TOKEN_REQUEST_DATA: 'client_id=2c03c507cadfe54ac028&client_secret=b20556f9854dda7cdb29c45aee9c1d01bcc0331e&grant_type=authorization_code&code='